export interface Template {
  id: number;
  category: string;
  categoryColor: string;
  title: string;
}

export interface TemplateCategory {
  name: string;
  color: string;
  icon: string;
  templates: Template[];
}

export const templateCategories: TemplateCategory[] = [
  {
    name: 'Маркетинг',
    color: '#D300E6',
    icon: 'MegaphoneIcon',
    templates: [
      { id: 0, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Создай продающий пост для соцсетей' },
      { id: 1, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Напиши привлекательное описание товара для каталога' },
      { id: 2, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Создай рекламный текст до 150 символов' },
      { id: 3, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Придумай идею для вирусного Reels или TikTok' },
      { id: 4, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Создай текст email-рассылки для клиентов' },
      { id: 5, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Составь контент-план на неделю для бизнеса' },
      { id: 105, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Создай привлекательный заголовок для статьи' },
      { id: 106, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Напиши описание для лендинга' },
      { id: 107, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Составь план запуска продукта' },
      { id: 108, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Создай текст для баннера' },
      { id: 109, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Придумай слоган для бренда' },
      { id: 110, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Составь план работы с инфлюенсерами' },
      { id: 111, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Создай текст для push-уведомления' },
      { id: 112, category: 'Маркетинг', categoryColor: '#80D300E6', title: 'Напиши описание для YouTube видео' },
    ],
  },
  {
    name: 'Продажи',
    color: '#007B0C',
    icon: 'ShoppingCartIcon',
    templates: [
      { id: 6, category: 'Продажи', categoryColor: '#80007B0C', title: 'Создай скрипт звонка для продажи услуги' },
      { id: 7, category: 'Продажи', categoryColor: '#80007B0C', title: 'Составь ответы на типичные возражения клиентов' },
      { id: 8, category: 'Продажи', categoryColor: '#80007B0C', title: 'Создай короткое коммерческое предложение' },
      { id: 9, category: 'Продажи', categoryColor: '#80007B0C', title: 'Напиши эффективный текст для общения с клиентом в чате' },
      { id: 10, category: 'Продажи', categoryColor: '#80007B0C', title: 'Подготовь финальную фразу для закрытия сделки' },
      { id: 11, category: 'Продажи', categoryColor: '#80007B0C', title: 'Создай короткое холодное сообщение для первого контакта' },
      { id: 113, category: 'Продажи', categoryColor: '#80007B0C', title: 'Составь план работы с воронкой продаж' },
      { id: 114, category: 'Продажи', categoryColor: '#80007B0C', title: 'Создай презентацию для клиента' },
      { id: 115, category: 'Продажи', categoryColor: '#80007B0C', title: 'Напиши текст для follow-up письма' },
      { id: 116, category: 'Продажи', categoryColor: '#80007B0C', title: 'Составь план работы с отложенными сделками' },
      { id: 117, category: 'Продажи', categoryColor: '#80007B0C', title: 'Создай систему мотивации для отдела продаж' },
      { id: 118, category: 'Продажи', categoryColor: '#80007B0C', title: 'Напиши текст для предложения скидки' },
      { id: 119, category: 'Продажи', categoryColor: '#80007B0C', title: 'Составь план работы с постоянными клиентами' },
      { id: 120, category: 'Продажи', categoryColor: '#80007B0C', title: 'Создай скрипт для работы с возражениями' },
    ],
  },
  {
    name: 'Стратегия',
    color: '#6F00E6',
    icon: 'LightBulbIcon',
    templates: [
      { id: 12, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Составь план развития бизнеса на 3 месяца' },
      { id: 13, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Сделай краткий анализ основных конкурентов' },
      { id: 14, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Придумай идеи для расширения линейки услуг' },
      { id: 15, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Составь SWOT-анализ компании' },
      { id: 16, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Предложи стратегию увеличения прибыли' },
      { id: 17, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Сформулируй уникальное торговое предложение' },
      { id: 121, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Составь долгосрочную стратегию развития' },
      { id: 122, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Создай план выхода на новый рынок' },
      { id: 123, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Составь план диверсификации бизнеса' },
      { id: 124, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Создай стратегию позиционирования бренда' },
      { id: 125, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Составь план партнерства с другими компаниями' },
      { id: 126, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Создай план масштабирования бизнеса' },
      { id: 127, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Составь план работы с кризисными ситуациями' },
      { id: 128, category: 'Стратегия', categoryColor: '#806F00E6', title: 'Создай стратегию работы с сезонностью' },
    ],
  },
  {
    name: 'Поддержка',
    color: '#9300E6',
    icon: 'LifebuoyIcon',
    templates: [
      { id: 18, category: 'Поддержка', categoryColor: '#809300E6', title: 'Составь вежливый ответ недовольному клиенту' },
      { id: 19, category: 'Поддержка', categoryColor: '#809300E6', title: 'Напиши корректное сообщение о задержке выполнения' },
      { id: 20, category: 'Поддержка', categoryColor: '#809300E6', title: 'Создай сообщение о подтверждении заказа' },
      { id: 21, category: 'Поддержка', categoryColor: '#809300E6', title: 'Составь инструкцию по использованию продукта' },
      { id: 22, category: 'Поддержка', categoryColor: '#809300E6', title: 'Создай корректное сообщение с извинением' },
      { id: 23, category: 'Поддержка', categoryColor: '#809300E6', title: 'Напиши профессиональный ответ на вопрос клиента' },
      { id: 129, category: 'Поддержка', categoryColor: '#809300E6', title: 'Создай шаблон ответа на частые вопросы' },
      { id: 130, category: 'Поддержка', categoryColor: '#809300E6', title: 'Составь план работы с жалобами' },
      { id: 131, category: 'Поддержка', categoryColor: '#809300E6', title: 'Напиши сообщение о решении проблемы' },
      { id: 132, category: 'Поддержка', categoryColor: '#809300E6', title: 'Создай систему оценки качества поддержки' },
      { id: 133, category: 'Поддержка', categoryColor: '#809300E6', title: 'Составь план обучения сотрудников поддержки' },
      { id: 134, category: 'Поддержка', categoryColor: '#809300E6', title: 'Напиши текст для базы знаний' },
      { id: 135, category: 'Поддержка', categoryColor: '#809300E6', title: 'Создай план работы с обратной связью клиентов' },
      { id: 136, category: 'Поддержка', categoryColor: '#809300E6', title: 'Составь план работы в нерабочее время' },
    ],
  },
  {
    name: 'Персонал',
    color: '#E67F00',
    icon: 'UserGroupIcon',
    templates: [
      { id: 24, category: 'Персонал', categoryColor: '#80E67F00', title: 'Составь корректную обратную связь сотруднику' },
      { id: 25, category: 'Персонал', categoryColor: '#80E67F00', title: 'Создай короткое объявление для коллектива' },
      { id: 26, category: 'Персонал', categoryColor: '#80E67F00', title: 'Напиши мотивационное сообщение для сотрудников' },
      { id: 27, category: 'Персонал', categoryColor: '#80E67F00', title: 'Составь список задач для сотрудника на день' },
      { id: 28, category: 'Персонал', categoryColor: '#80E67F00', title: 'Составь набор корпоративных правил' },
      { id: 29, category: 'Персонал', categoryColor: '#80E67F00', title: 'Создай текст привлекательной вакансии' },
      { id: 137, category: 'Персонал', categoryColor: '#80E67F00', title: 'Составь план проведения собеседования' },
      { id: 138, category: 'Персонал', categoryColor: '#80E67F00', title: 'Создай систему оценки сотрудников' },
      { id: 139, category: 'Персонал', categoryColor: '#80E67F00', title: 'Составь план командообразования' },
      { id: 140, category: 'Персонал', categoryColor: '#80E67F00', title: 'Напиши план развития карьеры сотрудника' },
      { id: 141, category: 'Персонал', categoryColor: '#80E67F00', title: 'Создай план работы с конфликтами в коллективе' },
      { id: 142, category: 'Персонал', categoryColor: '#80E67F00', title: 'Составь план удержания талантов' },
      { id: 143, category: 'Персонал', categoryColor: '#80E67F00', title: 'Создай систему наставничества' },
      { id: 144, category: 'Персонал', categoryColor: '#80E67F00', title: 'Составь план корпоративных мероприятий' },
    ],
  },
  {
    name: 'Аналитика',
    color: '#00AEEF',
    icon: 'ChartBarIcon',
    templates: [
      { id: 30, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Сделай краткий анализ продаж' },
      { id: 31, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Создай отчёт о результатах работы за неделю' },
      { id: 32, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Оцени эффективность рекламной кампании' },
      { id: 33, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Сделай прогноз спроса' },
      { id: 34, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Проанализируй слабые места бизнеса' },
      { id: 35, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Дай рекомендации по улучшению работы бизнеса' },
      { id: 36, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Создай отчёт о конверсии' },
      { id: 37, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Проанализируй поведение клиентов' },
      { id: 145, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Создай дашборд ключевых метрик' },
      { id: 146, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Проанализируй эффективность каналов привлечения' },
      { id: 147, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Составь отчёт о ROI маркетинговых кампаний' },
      { id: 148, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Создай анализ жизненного цикла клиента' },
      { id: 149, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Проанализируй сезонные тренды' },
      { id: 150, category: 'Аналитика', categoryColor: '#8000AEEF', title: 'Составь сравнительный анализ с конкурентами' },
    ],
  },
  {
    name: 'Финансы',
    color: '#FF69B4',
    icon: 'BanknotesIcon',
    templates: [
      { id: 38, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Составь финансовый план на квартал' },
      { id: 39, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Рассчитай точку безубыточности' },
      { id: 40, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Создай бюджет на месяц' },
      { id: 41, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Проанализируй расходы компании' },
      { id: 42, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Составь план оптимизации затрат' },
      { id: 43, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Рассчитай рентабельность проекта' },
      { id: 44, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Создай финансовый отчёт' },
      { id: 151, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Составь план инвестиций' },
      { id: 152, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Создай систему управления денежными потоками' },
      { id: 153, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Составь план работы с кредитами' },
      { id: 154, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Создай систему контроля расходов' },
      { id: 155, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Составь план налогового планирования' },
      { id: 156, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Создай прогноз финансовых показателей' },
      { id: 157, category: 'Финансы', categoryColor: '#80FF69B4', title: 'Составь план работы с дебиторской задолженностью' },
    ],
  },
  {
    name: 'HR',
    color: '#4682B4',
    icon: 'BriefcaseIcon',
    templates: [
      { id: 45, category: 'HR', categoryColor: '#804682B4', title: 'Составь описание должности' },
      { id: 46, category: 'HR', categoryColor: '#804682B4', title: 'Создай план адаптации нового сотрудника' },
      { id: 47, category: 'HR', categoryColor: '#804682B4', title: 'Составь план обучения сотрудников' },
      { id: 48, category: 'HR', categoryColor: '#804682B4', title: 'Создай систему оценки эффективности' },
      { id: 49, category: 'HR', categoryColor: '#804682B4', title: 'Напиши план развития команды' },
      { id: 50, category: 'HR', categoryColor: '#804682B4', title: 'Составь программу мотивации персонала' },
      { id: 158, category: 'HR', categoryColor: '#804682B4', title: 'Создай план адаптации новых сотрудников' },
      { id: 159, category: 'HR', categoryColor: '#804682B4', title: 'Составь систему компенсаций и льгот' },
      { id: 160, category: 'HR', categoryColor: '#804682B4', title: 'Создай план работы с увольнениями' },
      { id: 161, category: 'HR', categoryColor: '#804682B4', title: 'Составь план развития лидерских качеств' },
      { id: 162, category: 'HR', categoryColor: '#804682B4', title: 'Создай систему обратной связи от сотрудников' },
      { id: 163, category: 'HR', categoryColor: '#804682B4', title: 'Составь план работы с удаленными сотрудниками' },
      { id: 164, category: 'HR', categoryColor: '#804682B4', title: 'Создай план работы с внутренними коммуникациями' },
      { id: 165, category: 'HR', categoryColor: '#804682B4', title: 'Составь план работы с производительностью' },
    ],
  },
  {
    name: 'Операции',
    color: '#9370DB',
    icon: 'CogIcon',
    templates: [
      { id: 51, category: 'Операции', categoryColor: '#809370DB', title: 'Оптимизируй рабочие процессы' },
      { id: 52, category: 'Операции', categoryColor: '#809370DB', title: 'Составь план улучшения качества' },
      { id: 53, category: 'Операции', categoryColor: '#809370DB', title: 'Создай систему контроля качества' },
      { id: 54, category: 'Операции', categoryColor: '#809370DB', title: 'Составь план логистики' },
      { id: 55, category: 'Операции', categoryColor: '#809370DB', title: 'Оптимизируй цепочку поставок' },
      { id: 56, category: 'Операции', categoryColor: '#809370DB', title: 'Создай стандарты работы' },
      { id: 166, category: 'Операции', categoryColor: '#809370DB', title: 'Составь план автоматизации процессов' },
      { id: 167, category: 'Операции', categoryColor: '#809370DB', title: 'Создай систему управления рисками' },
      { id: 168, category: 'Операции', categoryColor: '#809370DB', title: 'Составь план работы с поставщиками' },
      { id: 169, category: 'Операции', categoryColor: '#809370DB', title: 'Создай план работы с инвентаризацией' },
      { id: 170, category: 'Операции', categoryColor: '#809370DB', title: 'Составь план работы с документацией' },
      { id: 171, category: 'Операции', categoryColor: '#809370DB', title: 'Создай систему мониторинга процессов' },
      { id: 172, category: 'Операции', categoryColor: '#809370DB', title: 'Составь план работы с инцидентами' },
      { id: 173, category: 'Операции', categoryColor: '#809370DB', title: 'Создай план непрерывного улучшения' },
    ],
  },
  {
    name: 'Розничная торговля',
    color: '#61B3F9',
    icon: 'ShoppingBagIcon',
    templates: [
      { id: 57, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Создай план мерчандайзинга' },
      { id: 58, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Составь стратегию ценообразования' },
      { id: 59, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Создай план акций и скидок' },
      { id: 60, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Оптимизируй выкладку товаров' },
      { id: 61, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Составь план работы с поставщиками' },
      { id: 62, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Создай систему управления запасами' },
      { id: 174, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Составь план работы с покупателями' },
      { id: 175, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Создай план работы с возвратами' },
      { id: 176, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Составь план работы с сезонными товарами' },
      { id: 177, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Создай систему работы с промокодами' },
      { id: 178, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Составь план работы с онлайн-продажами' },
      { id: 179, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Создай план работы с программами лояльности' },
      { id: 180, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Составь план работы с витриной' },
      { id: 181, category: 'Розничная торговля', categoryColor: '#8061B3F9', title: 'Создай план работы с персоналом магазина' },
    ],
  },
  {
    name: 'Производство',
    color: '#669484',
    icon: 'BuildingOfficeIcon',
    templates: [
      { id: 63, category: 'Производство', categoryColor: '#80669484', title: 'Оптимизируй производственный процесс' },
      { id: 64, category: 'Производство', categoryColor: '#80669484', title: 'Составь план контроля качества' },
      { id: 65, category: 'Производство', categoryColor: '#80669484', title: 'Создай систему управления производством' },
      { id: 66, category: 'Производство', categoryColor: '#80669484', title: 'Составь план технического обслуживания' },
      { id: 67, category: 'Производство', categoryColor: '#80669484', title: 'Оптимизируй использование ресурсов' },
      { id: 68, category: 'Производство', categoryColor: '#80669484', title: 'Создай план безопасности на производстве' },
      { id: 182, category: 'Производство', categoryColor: '#80669484', title: 'Составь план работы с оборудованием' },
      { id: 183, category: 'Производство', categoryColor: '#80669484', title: 'Создай систему управления производственным планом' },
      { id: 184, category: 'Производство', categoryColor: '#80669484', title: 'Составь план работы с браком' },
      { id: 185, category: 'Производство', categoryColor: '#80669484', title: 'Создай план работы с энергоэффективностью' },
      { id: 186, category: 'Производство', categoryColor: '#80669484', title: 'Составь план работы с экологией' },
      { id: 187, category: 'Производство', categoryColor: '#80669484', title: 'Создай план работы с инновациями' },
      { id: 188, category: 'Производство', categoryColor: '#80669484', title: 'Составь план работы с сертификацией' },
      { id: 189, category: 'Производство', categoryColor: '#80669484', title: 'Создай план работы с упаковкой' },
    ],
  },
  {
    name: 'IT/Технологии',
    color: '#3FC1C9',
    icon: 'ComputerDesktopIcon',
    templates: [
      { id: 69, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Составь техническое задание' },
      { id: 70, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Создай план разработки продукта' },
      { id: 71, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Составь план тестирования' },
      { id: 72, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Создай документацию проекта' },
      { id: 73, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Составь план внедрения системы' },
      { id: 74, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Создай план технической поддержки' },
      { id: 190, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Составь план работы с безопасностью данных' },
      { id: 191, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Создай план работы с облачными сервисами' },
      { id: 192, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Составь план работы с API' },
      { id: 193, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Создай план работы с DevOps' },
      { id: 194, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Составь план работы с мобильными приложениями' },
      { id: 195, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Создай план работы с искусственным интеллектом' },
      { id: 196, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Составь план работы с кибербезопасностью' },
      { id: 197, category: 'IT/Технологии', categoryColor: '#803FC1C9', title: 'Создай план работы с автоматизацией' },
    ],
  },
  {
    name: 'Здравоохранение',
    color: '#FF6B6B',
    icon: 'HeartIcon',
    templates: [
      { id: 75, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Составь план лечения пациента' },
      { id: 76, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Создай протокол медицинской процедуры' },
      { id: 77, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Составь план профилактических мероприятий' },
      { id: 78, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Создай систему управления медицинскими записями' },
      { id: 79, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Составь план работы с пациентами' },
      { id: 80, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Создай план повышения качества услуг' },
      { id: 198, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Составь план работы с пациентами' },
      { id: 199, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Создай план работы с медицинским оборудованием' },
      { id: 200, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Составь план работы с лекарствами' },
      { id: 201, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Создай план работы с медицинским персоналом' },
      { id: 202, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Составь план работы с санитарными нормами' },
      { id: 203, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Создай план работы с экстренными ситуациями' },
      { id: 204, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Составь план работы с медицинской документацией' },
      { id: 205, category: 'Здравоохранение', categoryColor: '#80FF6B6B', title: 'Создай план работы с профилактикой' },
    ],
  },
  {
    name: 'Образование',
    color: '#6C5CE7',
    icon: 'AcademicCapIcon',
    templates: [
      { id: 81, category: 'Образование', categoryColor: '#806C5CE7', title: 'Составь учебный план' },
      { id: 82, category: 'Образование', categoryColor: '#806C5CE7', title: 'Создай план урока' },
      { id: 83, category: 'Образование', categoryColor: '#806C5CE7', title: 'Составь программу обучения' },
      { id: 84, category: 'Образование', categoryColor: '#806C5CE7', title: 'Создай систему оценки знаний' },
      { id: 85, category: 'Образование', categoryColor: '#806C5CE7', title: 'Составь план работы с родителями' },
      { id: 86, category: 'Образование', categoryColor: '#806C5CE7', title: 'Создай план развития образовательного учреждения' },
      { id: 206, category: 'Образование', categoryColor: '#806C5CE7', title: 'Составь план работы с учениками' },
      { id: 207, category: 'Образование', categoryColor: '#806C5CE7', title: 'Создай план работы с родителями' },
      { id: 208, category: 'Образование', categoryColor: '#806C5CE7', title: 'Составь план работы с учебными материалами' },
      { id: 209, category: 'Образование', categoryColor: '#806C5CE7', title: 'Создай план работы с внеклассными мероприятиями' },
      { id: 210, category: 'Образование', categoryColor: '#806C5CE7', title: 'Составь план работы с профессиональным развитием' },
      { id: 211, category: 'Образование', categoryColor: '#806C5CE7', title: 'Создай план работы с инклюзивным образованием' },
      { id: 212, category: 'Образование', categoryColor: '#806C5CE7', title: 'Составь план работы с цифровыми технологиями' },
      { id: 213, category: 'Образование', categoryColor: '#806C5CE7', title: 'Создай план работы с оценкой качества образования' },
    ],
  },
  {
    name: 'Недвижимость',
    color: '#FD9853',
    icon: 'HomeIcon',
    templates: [
      { id: 87, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Составь описание объекта недвижимости' },
      { id: 88, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Создай план презентации объекта' },
      { id: 89, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Составь план работы с клиентами' },
      { id: 90, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Создай систему управления объектами' },
      { id: 91, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Составь план маркетинга недвижимости' },
      { id: 92, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Создай план оценки недвижимости' },
      { id: 214, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Составь план работы с арендаторами' },
      { id: 215, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Создай план работы с техническим обслуживанием' },
      { id: 216, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Составь план работы с юридическими вопросами' },
      { id: 217, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Создай план работы с инвестициями в недвижимость' },
      { id: 218, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Составь план работы с ремонтом' },
      { id: 219, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Создай план работы с коммунальными услугами' },
      { id: 220, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Составь план работы с безопасностью' },
      { id: 221, category: 'Недвижимость', categoryColor: '#80FD9853', title: 'Создай план работы с управлением объектами' },
    ],
  },
  {
    name: 'Ресторанный бизнес',
    color: '#FF9A9E',
    icon: 'CakeIcon',
    templates: [
      { id: 93, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Составь меню ресторана' },
      { id: 94, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Создай план работы кухни' },
      { id: 95, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Составь план обслуживания гостей' },
      { id: 96, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Создай систему управления заказами' },
      { id: 97, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Составь план маркетинга ресторана' },
      { id: 98, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Создай план работы с поставщиками' },
      { id: 222, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Составь план работы с персоналом ресторана' },
      { id: 223, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Создай план работы с санитарными нормами' },
      { id: 224, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Составь план работы с напитками' },
      { id: 225, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Создай план работы с мероприятиями' },
      { id: 226, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Составь план работы с доставкой' },
      { id: 227, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Создай план работы с рекламой' },
      { id: 228, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Составь план работы с отзывами' },
      { id: 229, category: 'Ресторанный бизнес', categoryColor: '#80FF9A9E', title: 'Создай план работы с сезонным меню' },
    ],
  },
  {
    name: 'Логистика',
    color: '#D8AA74',
    icon: 'TruckIcon',
    templates: [
      { id: 99, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Оптимизируй маршруты доставки' },
      { id: 100, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Составь план складской логистики' },
      { id: 101, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Создай систему управления транспортом' },
      { id: 102, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Составь план работы с перевозчиками' },
      { id: 103, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Создай план управления запасами' },
      { id: 104, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Оптимизируй цепочку поставок' },
      { id: 230, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Составь план работы с транспортом' },
      { id: 231, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Создай план работы с таможней' },
      { id: 232, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Составь план работы с упаковкой и маркировкой' },
      { id: 233, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Создай план работы с возвратами' },
      { id: 234, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Составь план работы с международной логистикой' },
      { id: 235, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Создай план работы с курьерскими службами' },
      { id: 236, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Составь план работы с отслеживанием грузов' },
      { id: 237, category: 'Логистика', categoryColor: '#80D8AA74', title: 'Создай план работы с логистическими партнерами' },
    ],
  },
  {
    name: 'Еженедельный отчет',
    color: '#79BAEF',
    icon: 'DocumentTextIcon',
    templates: [
      { id: 238, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Создай еженедельный отчет о работе' },
      { id: 253, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Составь отчет о выполненных задачах' },
      { id: 254, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Создай отчет о продажах за неделю' },
      { id: 255, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Составь отчет о работе команды' },
      { id: 256, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Создай отчет о достижениях за неделю' },
      { id: 257, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Составь отчет о маркетинговых активностях' },
      { id: 258, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Создай отчет о финансовых показателях' },
      { id: 259, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Составь отчет о работе с клиентами' },
      { id: 260, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Создай отчет о проектах за неделю' },
      { id: 261, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Составь отчет о производительности' },
      { id: 262, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Создай отчет о проблемах и решениях' },
      { id: 263, category: 'Еженедельный отчет', categoryColor: '#8079BAEF', title: 'Составь отчет о планах на следующую неделю' },
    ],
  },
  {
    name: 'Анализ рынка',
    color: '#EE96A5',
    icon: 'ChartPieIcon',
    templates: [
      { id: 239, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Проведи анализ рынка' },
      { id: 264, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Создай анализ конкурентов' },
      { id: 265, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Составь анализ целевой аудитории' },
      { id: 266, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Проведи анализ трендов в отрасли' },
      { id: 267, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Создай анализ ценовой политики' },
      { id: 268, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Составь анализ маркетинговых каналов' },
      { id: 269, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Проведи анализ сегментации рынка' },
      { id: 270, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Создай анализ продуктового портфеля' },
      { id: 271, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Составь анализ географического рынка' },
      { id: 272, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Проведи анализ потребительского поведения' },
      { id: 273, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Создай анализ рыночных возможностей' },
      { id: 274, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Составь анализ барьеров входа на рынок' },
      { id: 275, category: 'Анализ рынка', categoryColor: '#80EE96A5', title: 'Проведи анализ динамики рынка' },
    ],
  },
];

